INSERT INTO Evento(nome, desconto, ano) VALUES ('Happy Deals', 10, 2013);
INSERT INTO Evento(nome, desconto, ano) VALUES ('Your car is on Sale', 15, 2014);
INSERT INTO Evento(nome, desconto, ano) VALUES ('Best Offers', 25, 2015);
INSERT INTO Evento(nome, desconto, ano) VALUES ('Summer Car Time', 10, 2016);
INSERT INTO Evento(nome, desconto, ano) VALUES ('Best Car Deals', 5, 2017);
INSERT INTO Evento(nome, desconto, ano) VALUES ('Summer Deals', 7, 2018);
INSERT INTO Evento(nome, desconto, ano) VALUES ('Half of Half', 25, 2019);
INSERT INTO Evento(nome, desconto, ano) VALUES ('The Boss is Away', 10, 2020);


INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Vilma Langfiel', '700421838', 'vlangfield0@odnoklassniki.ru',2019 );
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Linus Werrilow', '535042484', 'lwerrilow1@reddit.com', 2014);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Daren Embra', '842984987', 'dembra2@yolasite.com', 2013);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Daloris Napoleon', '954093678', 'dnapoleon3@mac.com', 2015);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Ross Shynn', '462124015', 'rshynn4@elegantthemes.com', 2019);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Duncan Boraston', '542026363', 'dboraston5@mozilla.com', 2020);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Shir Skip', '591335782', 'sskip6@slideshare.net', 2016);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Gawain Sympson', '604827748', 'gsympson7@nytimes.com', 2019);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Alfy Awcoate', '717902003', 'aawcoate8@fotki.com', 2017);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Buckridge, Grimes and Green', '353721261', 'rizakoff9@fema.gov',2017);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Spinka, Wolf and Abshire', '939910655', 'jelizabetha@wunderground.com', 2020);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Beer LLC', '288988572', 'blocknerb@com.com', 2018);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Blick, Huels and Schamberger', '650995853', 'vmacgrathc@dyndns.org', 2017);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Stracke Group', '232788400', 'rshipperbottomd@bloglines.com', 2016);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Sipes, Koss and Langosh', '456869642', 'emullindere@youku.com', 2013);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Lehner, Donelly and Stroman', '923015432', 'blustyf@skyrock.com', 2014);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Glover, Barrows and Smith', '938948924', 'jadamog@fema.gov', 2015);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Pacocha, Konopelski and Stiedemann', '112993605', 'gdrewetth@theguardian.com', 2019);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Howe, Hills and Collins', '350790286', 'cmaccafferyi@weebly.com', 2017);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Hamill Inc', '518692915', 'bmatiebej@github.com', 2017);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Roberto Robardey', '516286616', 'tmannoochk@pbs.org', 2014);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Othilia McKilroe', '316148720', 'msigsworthl@wsj.com', 2019);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Marna McCarver', '920928238', 'rrobardeym@mapy.cz', 2016);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Craggie Faloon', '464524681', 'omckilroen@newsvine.com', 2020);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Wallie Lawrinson', '246432900', 'mmccarvero@kickstarter.com', 2013);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Everard Ellwell', '769362902', 'cfalloonp@tinyurl.com', 2018);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Gerianne Darnbrough', '160123524', 'wlawrinsonq@printfriendly.com', 2017);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Eyde di Rocca', '219784625', 'eellwellr@homestead.com', 2013);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Lock Nowakowska', '468675878', 'gdarnbroughs@wufoo.com', 2016);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Cummerata, Smith and Leffler', '547794676', 'edit@google.cn', 2020);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Friesen-Farrell', '705197000', 'lnowakowskau@jimdo.com', 2015);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Watsica, Davis and Nikolaus', '882007737', 'docleryv@go.com', 2019);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Christiansen and Sons', '642316664', 'rneillansw@accuweather.com', 2013);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Collins, Lockman and Barton', '546040409', 'otrankx@ocn.ne.jp', 2016);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Hessel, Moore and Parisian', '209130777', 'esteffensy@mapquest.com', 2019);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Strosin-Schuppe', '470824540', 'sscadez@samsung.com', 2020);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Beahan and Sons', '912846987', 'ddun10@ucoz.com', 2013);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Osinski, Mills and Huels', '281380932', 'broll11@google.co.jp', 2015);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Ebert-Littel', '124691101', 'dtozer12@prlog.org', 2017);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Nitzsche, Schamberger and Stroman', '146477166', 'tbantock13@barnesandnoble.com', 2018);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Gretna Esplin', '270633804', 'hcalderonello14@plala.or.jp', 2018);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Isabella Priter', '369010889', 'rofeeney15@yellowbook.com', 2020);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Cariotta Krale', '885545233', 'gtames16@cbc.ca', 2016);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Gusty Bixley', '163917355', 'mwoan17@canalblog.com', 2014);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Albina Meah', '587894608', 'vlambot18@sciencedaily.com', 2015);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Hanni Cordelette', '345593153', 'ronthank19@istockphoto.com', 2015);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Malina Dachs', '886566469', 'gesplin1a@nhs.uk', 2015);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Wilmar Pirdue', '436307410', 'ipriter1b@ft.com', 2013);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Howie Blamey', '321079084', 'ckrale1c@slate.com', 2014);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Talia Sappson', '125188492', 'gbixley1d@studiopress.com', 2019);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Eziechiele Fishbourne', '387788195', 'ameah1e@ucsd.edu', 2015);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Sonnnie Edmonston', '178023901', 'hcordelette1f@wordpress.com', 2014);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Lettie Cawdell', '999301707', 'mdachs1g@yellowpages.com', 2016);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Wunsch LLC', '308720078', 'wpirdue1h@businesswire.com', 2013);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Schinner-Klocko', '864594464', 'hblamey1i@stumbleupon.com', 2020);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Friesen, Wolff and Considine', '158586297', 'tsappson1j@nsw.gov.au', 2016);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Lang-Cormier', '509572653', 'efishbourne1k@cbslocal.com', 2020);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Terry Inc', '893949245', 'sedmonston1l@fc2.com', 2013);
INSERT INTO Utilizador(nome, telefone, email, evento) VALUES ('Kihn Inc', '981113689', 'lcawdell1m@123-reg.co.uk', 2013);

INSERT INTO UtilizadorParticular(email) VALUES('vlangfield0@odnoklassniki.ru');
INSERT INTO UtilizadorParticular(email) VALUES('lwerrilow1@reddit.com');
INSERT INTO UtilizadorParticular(email) VALUES('dembra2@yolasite.com');
INSERT INTO UtilizadorParticular(email) VALUES('dnapoleon3@mac.com');
INSERT INTO UtilizadorParticular(email) VALUES('rshynn4@elegantthemes.com');
INSERT INTO UtilizadorParticular(email) VALUES('dboraston5@mozilla.com');
INSERT INTO UtilizadorParticular(email) VALUES('sskip6@slideshare.net');
INSERT INTO UtilizadorParticular(email) VALUES('gsympson7@nytimes.com');
INSERT INTO UtilizadorParticular(email) VALUES('aawcoate8@fotki.com');
INSERT INTO UtilizadorParticular(email) VALUES('rizakoff9@fema.gov');
INSERT INTO UtilizadorParticular(email) VALUES('jelizabetha@wunderground.com');
INSERT INTO UtilizadorParticular(email) VALUES('tmannoochk@pbs.org');
INSERT INTO UtilizadorParticular(email) VALUES('msigsworthl@wsj.com');
INSERT INTO UtilizadorParticular(email) VALUES('rrobardeym@mapy.cz');
INSERT INTO UtilizadorParticular(email) VALUES('omckilroen@newsvine.com');
INSERT INTO UtilizadorParticular(email) VALUES('mmccarvero@kickstarter.com');
INSERT INTO UtilizadorParticular(email) VALUES('cfalloonp@tinyurl.com');
INSERT INTO UtilizadorParticular(email) VALUES('wlawrinsonq@printfriendly.com');
INSERT INTO UtilizadorParticular(email) VALUES('eellwellr@homestead.com');
INSERT INTO UtilizadorParticular(email) VALUES('gdarnbroughs@wufoo.com');
INSERT INTO UtilizadorParticular(email) VALUES('hcalderonello14@plala.or.jp');
INSERT INTO UtilizadorParticular(email) VALUES('rofeeney15@yellowbook.com');
INSERT INTO UtilizadorParticular(email) VALUES('gtames16@cbc.ca');
INSERT INTO UtilizadorParticular(email) VALUES('mwoan17@canalblog.com');
INSERT INTO UtilizadorParticular(email) VALUES('vlambot18@sciencedaily.com');
INSERT INTO UtilizadorParticular(email) VALUES('ronthank19@istockphoto.com');
INSERT INTO UtilizadorParticular(email) VALUES('gesplin1a@nhs.uk');
INSERT INTO UtilizadorParticular(email) VALUES('ipriter1b@ft.com');
INSERT INTO UtilizadorParticular(email) VALUES('ckrale1c@slate.com');
INSERT INTO UtilizadorParticular(email) VALUES('gbixley1d@studiopress.com');
INSERT INTO UtilizadorParticular(email) VALUES('ameah1e@ucsd.edu');
INSERT INTO UtilizadorParticular(email) VALUES('hcordelette1f@wordpress.com');
INSERT INTO UtilizadorParticular(email) VALUES('mdachs1g@yellowpages.com');

INSERT INTO UtilizadorProfissional(email, nif) VALUES('blocknerb@com.com', '761144657');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('vmacgrathc@dyndns.org', '339937270');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('rshipperbottomd@bloglines.com', '439822455');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('emullindere@youku.com', '828998490');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('blustyf@skyrock.com', '611353051');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('jadamog@fema.gov', '367530673');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('gdrewetth@theguardian.com', '386402583');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('cmaccafferyi@weebly.com', '337185111');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('bmatiebej@github.com', '466502990');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('edit@google.cn', '755058894');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('lnowakowskau@jimdo.com', '277717228');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('docleryv@go.com', '666037077');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('rneillansw@accuweather.com', '633732011');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('otrankx@ocn.ne.jp', '456865047');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('esteffensy@mapquest.com', '810403431');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('sscadez@samsung.com', '742207392');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('ddun10@ucoz.com', '330208300');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('broll11@google.co.jp', '870507279');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('dtozer12@prlog.org', '153084823');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('tbantock13@barnesandnoble.com', '934668938');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('wpirdue1h@businesswire.com', '253523859');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('hblamey1i@stumbleupon.com', '881857211');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('tsappson1j@nsw.gov.au', '281521521');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('efishbourne1k@cbslocal.com', '692773529');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('sedmonston1l@fc2.com', '503375088');
INSERT INTO UtilizadorProfissional(email, nif) VALUES('lcawdell1m@123-reg.co.uk', '203110904');
